// Idempotent MySQL migrations. Safe to run on every boot: every
// statement is IF NOT EXISTS / guarded, versions are recorded in
// `schema_migrations`, and nothing destructive ever runs here.
import { sql } from "drizzle-orm";
import { getDb, selectRows } from "./index.js";
import { logger } from "../core/logger.js";

const MIGRATIONS = [
    {
        version: "001_initial",
        statements: [
            `CREATE TABLE IF NOT EXISTS \`schema_migrations\` (\`version\` VARCHAR(191) NOT NULL PRIMARY KEY, \`applied_at\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Session\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`tokenHash\` VARCHAR(191) NOT NULL UNIQUE, \`userId\` VARCHAR(191) NOT NULL, \`guildId\` TEXT NULL, \`expiresAt\` TIMESTAMP(3) NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), INDEX \`session_user\` (\`userId\`), INDEX \`session_expires\` (\`expiresAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`DashboardGuild\` (\`userId\` VARCHAR(191) NOT NULL, \`guildId\` VARCHAR(191) NOT NULL, \`name\` TEXT NULL, \`icon\` TEXT NULL, \`permissions\` TEXT NOT NULL, \`manage\` TINYINT(1) NOT NULL DEFAULT 0, \`owner\` TINYINT(1) NOT NULL DEFAULT 0, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (\`userId\`, \`guildId\`), INDEX \`dashguild_user\` (\`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`GuildConfig\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`logChannelId\` TEXT NULL, \`modLogChannelId\` TEXT NULL, \`welcomeChannelId\` TEXT NULL, \`goodbyeChannelId\` TEXT NULL, \`ticketCategoryId\` TEXT NULL, \`ticketLogChannelId\` TEXT NULL, \`staffRoleIds\` TEXT NOT NULL, \`moderatorRoleIds\` TEXT NOT NULL, \`ignoredChannelIds\` TEXT NOT NULL, \`ignoredRoleIds\` TEXT NOT NULL, \`ignoredUserIds\` TEXT NOT NULL, \`modules\` TEXT NOT NULL, \`automod\` TEXT NOT NULL, \`orders\` TEXT NOT NULL, \`prefix\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`GuildBranding\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`displayName\` TEXT NULL, \`avatarUrl\` TEXT NULL, \`bannerUrl\` TEXT NULL, \`nickname\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`LevelConfig\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`xpMultiplier\` FLOAT NOT NULL DEFAULT 1, \`channelMultipliers\` TEXT NOT NULL, \`roleRewards\` TEXT NOT NULL, \`streakEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`announceChannelId\` TEXT NULL, \`antiFarmEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`prestigeEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`EconomyConfig\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`dailyAmount\` INT NOT NULL DEFAULT 100, \`weeklyAmount\` INT NOT NULL DEFAULT 500, \`shopEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`tradingEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`jobsEnabled\` TINYINT(1) NOT NULL DEFAULT 1, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Case\` (\`id\` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`caseNumber\` INT NOT NULL, \`targetId\` VARCHAR(191) NOT NULL, \`targetTag\` TEXT NOT NULL, \`moderatorId\` TEXT NOT NULL, \`moderatorTag\` TEXT NOT NULL, \`action\` TEXT NOT NULL, \`reason\` TEXT NULL, \`duration\` TEXT NULL, \`durationMs\` BIGINT NULL, \`resolved\` TINYINT(1) NOT NULL DEFAULT 0, \`resolvedById\` TEXT NULL, \`resolvedByTag\` TEXT NULL, \`resolvedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`metadata\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`case_guild_number\` (\`guildId\`, \`caseNumber\`), INDEX \`case_guild_target\` (\`guildId\`, \`targetId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`CaseNote\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`caseNumber\` INT NULL, \`targetId\` VARCHAR(191) NOT NULL, \`authorId\` TEXT NOT NULL, \`authorTag\` TEXT NULL, \`content\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`casenote_guild_target\` (\`guildId\`, \`targetId\`), INDEX \`casenote_guild_case\` (\`guildId\`, \`caseNumber\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Appeal\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`caseNumber\` INT NOT NULL, \`appellantId\` TEXT NOT NULL, \`reason\` TEXT NOT NULL, \`status\` TEXT NOT NULL, \`reviewerId\` TEXT NULL, \`reviewerTag\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), INDEX \`appeal_guild_status\` (\`guildId\`, \`status\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`AuditLog\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`actorId\` TEXT NULL, \`targetId\` TEXT NULL, \`action\` TEXT NOT NULL, \`category\` VARCHAR(191) NOT NULL, \`details\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`audit_guild_created\` (\`guildId\`, \`createdAt\`), INDEX \`audit_guild_category\` (\`guildId\`, \`category\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`RaidIncident\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`type\` TEXT NOT NULL, \`risk\` INT NOT NULL, \`details\` TEXT NULL, \`resolved\` TINYINT(1) NOT NULL DEFAULT 0, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`raid_guild_created\` (\`guildId\`, \`createdAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketType\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`panelType\` TEXT NOT NULL, \`key\` VARCHAR(191) NOT NULL, \`displayName\` TEXT NOT NULL, \`description\` TEXT NULL, \`emoji\` TEXT NULL, \`enabled\` TINYINT(1) NOT NULL DEFAULT 1, \`categoryId\` TEXT NULL, \`staffRoleIds\` TEXT NOT NULL, \`moderatorRoleIds\` TEXT NOT NULL, \`channelPrefix\` TEXT NULL, \`welcomeMessage\` TEXT NULL, \`instructions\` TEXT NULL, \`bannerUrl\` TEXT NULL, \`priority\` TEXT NOT NULL, \`cooldown\` INT NOT NULL DEFAULT 0, \`maxOpen\` INT NOT NULL DEFAULT 1, \`allowClaim\` TINYINT(1) NOT NULL DEFAULT 1, \`questions\` TEXT NOT NULL, \`formQuestions\` TEXT NOT NULL, \`autoCloseMinutes\` INT NOT NULL DEFAULT 30, UNIQUE KEY \`tickettype_guild_key\` (\`guildId\`, \`key\`), INDEX \`tickettype_guild_panel\` (\`guildId\`, \`panelType\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Ticket\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` VARCHAR(191) NOT NULL UNIQUE, \`openerId\` VARCHAR(191) NOT NULL, \`typeId\` TEXT NULL, \`panelType\` TEXT NULL, \`status\` TEXT NOT NULL, \`priority\` TEXT NOT NULL, \`customName\` TEXT NULL, \`claimedById\` TEXT NULL, \`assignedById\` TEXT NULL, \`assignedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`closedById\` TEXT NULL, \`closeReason\` TEXT NULL, \`lastMessageAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`workspaceMessageId\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`closedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`transcript\` TEXT NULL, INDEX \`ticket_guild_opener\` (\`guildId\`, \`openerId\`), INDEX \`ticket_guild_status\` (\`guildId\`, \`status\`(191)), INDEX \`ticket_guild_closed\` (\`guildId\`, \`closedAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketNote\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`ticketId\` VARCHAR(191) NOT NULL, \`authorId\` TEXT NOT NULL, \`content\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`ticketnote_guild_ticket\` (\`guildId\`, \`ticketId\`), INDEX \`ticketnote_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketHistory\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`ticketId\` VARCHAR(191) NOT NULL, \`event\` VARCHAR(191) NOT NULL, \`actorId\` TEXT NULL, \`details\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`tickethist_guild_ticket\` (\`guildId\`, \`ticketId\`), INDEX \`tickethist_guild_event\` (\`guildId\`, \`event\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketFormResponse\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`ticketId\` VARCHAR(191) NOT NULL, \`questions\` TEXT NOT NULL, \`answers\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`ticketform_guild_ticket\` (\`guildId\`, \`ticketId\`), INDEX \`ticketform_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketRating\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` VARCHAR(191) NOT NULL, \`raterId\` VARCHAR(191) NOT NULL, \`rating\` INT NOT NULL, \`feedback\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`ticketrating_guild_chan_rater\` (\`guildId\`, \`channelId\`, \`raterId\`), INDEX \`ticketrating_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketSummary\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`type\` TEXT NULL, \`status\` TEXT NOT NULL, \`priority\` TEXT NOT NULL, \`openedBy\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL, \`closedAt\` TIMESTAMP(3) NULL DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`TicketDetail\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`typeId\` TEXT NULL, \`openerId\` TEXT NOT NULL, \`claimedById\` TEXT NULL, \`assignedById\` TEXT NULL, \`status\` TEXT NOT NULL, \`priority\` TEXT NOT NULL, \`closeReason\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL, \`closedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`transcript\` TEXT NULL, \`formAnswers\` TEXT NULL, \`notes\` TEXT NULL, \`history\` TEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Panel\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`panelType\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NULL, \`messageId\` TEXT NULL, \`title\` TEXT NULL, \`description\` TEXT NULL, \`bannerUrl\` TEXT NULL, \`bannerChannelId\` TEXT NULL, \`bannerMessageId\` TEXT NULL, \`thumbnailUrl\` TEXT NULL, \`embedColor\` INT NULL, \`footerText\` TEXT NULL, \`footerIcon\` TEXT NULL, \`enabled\` TINYINT(1) NOT NULL DEFAULT 0, \`config\` TEXT NOT NULL, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`panel_guild_type\` (\`guildId\`, \`panelType\`), INDEX \`panel_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Order\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` VARCHAR(191) NOT NULL UNIQUE, \`openerId\` TEXT NOT NULL, \`claimedById\` TEXT NULL, \`category\` TEXT NOT NULL, \`status\` TEXT NOT NULL, \`brief\` TEXT NULL, \`budget\` TEXT NULL, \`deadline\` TIMESTAMP(3) NULL DEFAULT NULL, \`references\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`closedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`transcript\` TEXT NULL, INDEX \`order_guild_status\` (\`guildId\`, \`status\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Xp\` (\`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`xp\` INT NOT NULL DEFAULT 0, \`level\` INT NOT NULL DEFAULT 0, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (\`guildId\`, \`userId\`), INDEX \`xp_guild_level\` (\`guildId\`, \`level\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`XpStreak\` (\`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`streak\` INT NOT NULL DEFAULT 0, \`longest\` INT NOT NULL DEFAULT 0, \`lastXpAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (\`guildId\`, \`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Economy\` (\`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`balance\` INT NOT NULL DEFAULT 0, \`bank\` INT NOT NULL DEFAULT 0, \`dailyStreak\` INT NOT NULL DEFAULT 0, \`weeklyStreak\` INT NOT NULL DEFAULT 0, \`lastDaily\` TIMESTAMP(3) NULL DEFAULT NULL, \`lastWeekly\` TIMESTAMP(3) NULL DEFAULT NULL, \`lastWork\` TIMESTAMP(3) NULL DEFAULT NULL, \`lastCrime\` TIMESTAMP(3) NULL DEFAULT NULL, \`lastRob\` TIMESTAMP(3) NULL DEFAULT NULL, \`totalEarned\` INT NOT NULL DEFAULT 0, \`totalSpent\` INT NOT NULL DEFAULT 0, \`crimesCommitted\` INT NOT NULL DEFAULT 0, \`crimesFailed\` INT NOT NULL DEFAULT 0, \`timesRobbed\` INT NOT NULL DEFAULT 0, \`slotsPlayed\` INT NOT NULL DEFAULT 0, \`slotsWon\` INT NOT NULL DEFAULT 0, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (\`guildId\`, \`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`EconomyTransaction\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`type\` TEXT NOT NULL, \`amount\` INT NOT NULL, \`balanceAfter\` INT NOT NULL, \`meta\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`ecotx_guild_user\` (\`guildId\`, \`userId\`), INDEX \`ecotx_guild_created\` (\`guildId\`, \`createdAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`ShopItem\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`name\` VARCHAR(191) NOT NULL, \`description\` TEXT NULL, \`price\` INT NOT NULL, \`roleId\` TEXT NULL, \`emoji\` TEXT NULL, \`stock\` INT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`shopitem_guild_name\` (\`guildId\`, \`name\`), INDEX \`shopitem_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`ShopInventory\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`itemId\` VARCHAR(191) NOT NULL, \`quantity\` INT NOT NULL DEFAULT 1, \`purchasedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`shopinv_guild_user_item\` (\`guildId\`, \`userId\`, \`itemId\`), INDEX \`shopinv_guild_user\` (\`guildId\`, \`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Afk\` (\`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`reason\` TEXT NULL, \`since\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), PRIMARY KEY (\`guildId\`, \`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Poll\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`messageId\` VARCHAR(191) NOT NULL UNIQUE, \`authorId\` TEXT NOT NULL, \`question\` TEXT NOT NULL, \`options\` TEXT NOT NULL, \`endsAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Reminder\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`userId\` TEXT NOT NULL, \`message\` TEXT NOT NULL, \`remindAt\` TIMESTAMP(3) NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`reminder_at\` (\`remindAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Suggestion\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`messageId\` VARCHAR(191) NOT NULL UNIQUE, \`authorId\` TEXT NOT NULL, \`content\` TEXT NOT NULL, \`status\` TEXT NOT NULL, \`reviewerId\` TEXT NULL, \`reviewNote\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`suggestion_guild_status\` (\`guildId\`, \`status\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`StarboardConfig\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`channelId\` TEXT NOT NULL, \`threshold\` INT NOT NULL DEFAULT 3, \`emoji\` TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`StarboardEntry\` (\`id\` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`originalId\` VARCHAR(191) NOT NULL, \`starboardId\` TEXT NOT NULL, \`starCount\` INT NOT NULL DEFAULT 0, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), UNIQUE KEY \`starentry_guild_orig\` (\`guildId\`, \`originalId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`ReactionRole\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`messageId\` VARCHAR(191) NOT NULL, \`emoji\` VARCHAR(191) NOT NULL, \`roleId\` TEXT NOT NULL, UNIQUE KEY \`rr_guild_msg_emoji\` (\`guildId\`, \`messageId\`, \`emoji\`), INDEX \`rr_guild\` (\`guildId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Giveaway\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`channelId\` TEXT NOT NULL, \`messageId\` VARCHAR(191) NOT NULL UNIQUE, \`hostId\` TEXT NULL, \`hostTag\` TEXT NULL, \`prize\` TEXT NOT NULL, \`winners\` INT NOT NULL DEFAULT 1, \`endsAt\` TIMESTAMP(3) NOT NULL, \`ended\` TINYINT(1) NOT NULL DEFAULT 0, \`status\` TEXT NOT NULL, \`winnerIds\` TEXT NOT NULL, \`entryCount\` INT NOT NULL DEFAULT 0, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`giveaway_ends\` (\`endsAt\`), INDEX \`giveaway_guild_status\` (\`guildId\`, \`status\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`GiveawayEntry\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`giveawayId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`enteredAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`giveentry_give_user\` (\`giveawayId\`, \`userId\`), INDEX \`giveentry_guild\` (\`guildId\`), INDEX \`giveentry_give\` (\`giveawayId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Achievement\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` TEXT NULL, \`key\` VARCHAR(191) NOT NULL, \`name\` TEXT NOT NULL, \`description\` TEXT NULL, \`category\` TEXT NOT NULL, \`icon\` TEXT NULL, \`rewards\` TEXT NOT NULL, \`conditions\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY \`achieve_guild_key\` (\`guildId\`(191), \`key\`), INDEX \`achieve_guild\` (\`guildId\`(191))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`UserAchievement\` (\`guildId\` VARCHAR(191) NOT NULL, \`userId\` VARCHAR(191) NOT NULL, \`achievementId\` VARCHAR(191) NOT NULL, \`progress\` INT NOT NULL DEFAULT 0, \`unlocked\` TINYINT(1) NOT NULL DEFAULT 0, \`unlockedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), PRIMARY KEY (\`guildId\`, \`userId\`, \`achievementId\`), INDEX \`userachieve_guild_user\` (\`guildId\`, \`userId\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`AutomationRule\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`name\` TEXT NULL, \`enabled\` TINYINT(1) NOT NULL DEFAULT 1, \`trigger\` VARCHAR(191) NOT NULL, \`conditions\` TEXT NOT NULL, \`actions\` TEXT NOT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), \`updatedAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), INDEX \`autorule_guild_trigger\` (\`guildId\`, \`trigger\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`Backup\` (\`id\` VARCHAR(36) NOT NULL PRIMARY KEY, \`guildId\` VARCHAR(191) NOT NULL, \`data\` TEXT NOT NULL, \`version\` INT NOT NULL DEFAULT 1, \`createdById\` TEXT NOT NULL, \`createdByTag\` TEXT NULL, \`createdAt\` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX \`backup_guild_created\` (\`guildId\`, \`createdAt\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
            `CREATE TABLE IF NOT EXISTS \`FortressState\` (\`guildId\` VARCHAR(191) NOT NULL PRIMARY KEY, \`active\` TINYINT(1) NOT NULL DEFAULT 0, \`enabledById\` TEXT NULL, \`enabledByTag\` TEXT NULL, \`startedAt\` TIMESTAMP(3) NULL DEFAULT NULL, \`snapshot\` TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
        ],
    },
];

export async function runMigrations() {
    const db = getDb();
    for (const m of MIGRATIONS) {
        let applied = false;
        try {
            const rows = await selectRows(db.execute(sql`SELECT \`version\` FROM \`schema_migrations\` WHERE \`version\` = ${m.version}`));
            applied = rows.length > 0;
        } catch (e) {
            // schema_migrations itself doesn't exist yet on a fresh DB.
            applied = false;
        }
        if (applied) {
            logger.info("db", `migration ${m.version} already applied`);
            continue;
        }
        for (const stmt of m.statements) {
            await db.execute(sql.raw(stmt));
        }
        await db.execute(sql`INSERT INTO \`schema_migrations\` (\`version\`) VALUES (${m.version})`);
        logger.info("db", `migration ${m.version} applied (${m.statements.length} statements)`);
    }
}
